influxdb:
    image: anarcher/influxdb:0.9.5-rc2
    ports:
        - "8083:8083"
        - "8086:8086"
    environment:
        - PRE_CREATE_DB="telegraf"
                                       #
telegraf:
    build: .
    dockerfile: telegraf.Dockerfile
    volumes: 
        - /sys:/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock

chronograf:
    build: .
    dockerfile: chronograf.Dockerfile
    ports:
        - "8081:80"
