FROM ubuntu:14.04
RUN apt-get update -y
RUN apt-get install curl -y
RUN curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
#RUN apt-get install gitlab-ce=8.0.2-ce.1 -y
